name: Matchstick Ci/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  runs-on: ubuntu-latest
  steps:
  - name: Compiled program work
  run: make
  - name: run fclean
  run: make fclean

